// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankReportingDb.Models;

public partial class NCurrency
{
    public string Id { get; set; }

    public string Name { get; set; }

    public virtual ICollection<RTransaction> RTransactions { get; set; } = new List<RTransaction>();
}