// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankReportingDb.Models;

public partial class RMerchant
{
    public decimal Id { get; set; }

    public decimal? IdPartner { get; set; }

    public string Name { get; set; }

    public DateTime? BoardingDate { get; set; }

    public string Url { get; set; }

    public string Country { get; set; }

    public string Address1 { get; set; }

    public string Addres2 { get; set; }

    public virtual RPartner IdPartnerNavigation { get; set; }

    public virtual ICollection<RTransaction> RTransactions { get; set; } = new List<RTransaction>();
}