// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankReportingDb.Models;

public partial class RTransaction
{
    public decimal Id { get; set; }

    public decimal IdMerchant { get; set; }

    public DateTime CreateDate { get; set; }

    public int IdDirection { get; set; }

    public decimal Amount { get; set; }

    public int IdCcy { get; set; }

    public string DebtorIban { get; set; }

    public string BeneficiaryIban { get; set; }

    public bool? Status { get; set; }

    public string ExternalId { get; set; }

    public decimal? IdTransactionFile { get; set; }

    public virtual RMerchant IdMerchantNavigation { get; set; }
}