// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BankReportingDb.Models;

public partial class RTransactionFile
{
    public decimal Id { get; set; }

    public string Name { get; set; }

    public byte[] Contents { get; set; }

    public string ContentType { get; set; }

    public DateTime FileDate { get; set; }

    public DateTime DateCreated { get; set; }
}