//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankReportingLibrary.BL.Res {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ImportTransaction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ImportTransaction() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BankReportingLibrary.BL.Res.ImportTransaction", typeof(ImportTransaction).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount is required.
        /// </summary>
        internal static string lAmountRequired {
            get {
                return ResourceManager.GetString("lAmountRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary.
        /// </summary>
        internal static string lBeneficiary {
            get {
                return ResourceManager.GetString("lBeneficiary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beneficiary is required.
        /// </summary>
        internal static string lBeneficiaryRequired {
            get {
                return ResourceManager.GetString("lBeneficiaryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create date is required.
        /// </summary>
        internal static string lCreateDateRequired {
            get {
                return ResourceManager.GetString("lCreateDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount currency is invalid.
        /// </summary>
        internal static string lCurrencyInvalid {
            get {
                return ResourceManager.GetString("lCurrencyInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency is required.
        /// </summary>
        internal static string lCurrencyRequired {
            get {
                return ResourceManager.GetString("lCurrencyRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor.
        /// </summary>
        internal static string lDebtor {
            get {
                return ResourceManager.GetString("lDebtor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debtor is required.
        /// </summary>
        internal static string lDebtorRequired {
            get {
                return ResourceManager.GetString("lDebtorRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount direction is invalid.
        /// </summary>
        internal static string lDirectionInvalid {
            get {
                return ResourceManager.GetString("lDirectionInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direction is required.
        /// </summary>
        internal static string lDirectionRequired {
            get {
                return ResourceManager.GetString("lDirectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions successful export.
        /// </summary>
        internal static string lExportOk {
            get {
                return ResourceManager.GetString("lExportOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External id max length is 50 symbols.
        /// </summary>
        internal static string lExternalIdMaxLength {
            get {
                return ResourceManager.GetString("lExternalIdMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File date is required.
        /// </summary>
        internal static string lFileDateRequired {
            get {
                return ResourceManager.GetString("lFileDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN max length is 22 symbols.
        /// </summary>
        internal static string lIbanMaxLength {
            get {
                return ResourceManager.GetString("lIbanMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iban is required.
        /// </summary>
        internal static string lIbanRequired {
            get {
                return ResourceManager.GetString("lIbanRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import succesful.
        /// </summary>
        internal static string lImportOk {
            get {
                return ResourceManager.GetString("lImportOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid model.
        /// </summary>
        internal static string lInvalidModel {
            get {
                return ResourceManager.GetString("lInvalidModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid xml.
        /// </summary>
        internal static string lInvalidXml {
            get {
                return ResourceManager.GetString("lInvalidXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data.
        /// </summary>
        internal static string lNoData {
            get {
                return ResourceManager.GetString("lNoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merchant is required.
        /// </summary>
        internal static string lNoMerchant {
            get {
                return ResourceManager.GetString("lNoMerchant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No transactions in file.
        /// </summary>
        internal static string lNoTransactions {
            get {
                return ResourceManager.GetString("lNoTransactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction.
        /// </summary>
        internal static string lTransaction {
            get {
                return ResourceManager.GetString("lTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string lValueRequired {
            get {
                return ResourceManager.GetString("lValueRequired", resourceCulture);
            }
        }
    }
}
