// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using BankReportingDb.Models;
using Microsoft.EntityFrameworkCore;

namespace BankReportingDb.Context;

public partial class DB : DbContext
{
    public DB(DbContextOptions<DB> options)
        : base(options)
    {
    }

    public virtual DbSet<RMerchant> RMerchants { get; set; }

    public virtual DbSet<RPartner> RPartners { get; set; }

    public virtual DbSet<RTransaction> RTransactions { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<RMerchant>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__r_mercha__3213E83F2F2EF566");

            entity.ToTable("r_merchant");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("id");
            entity.Property(e => e.Addres2)
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("addres_2");
            entity.Property(e => e.Address1)
                .IsRequired()
                .HasMaxLength(150)
                .IsUnicode(false)
                .HasColumnName("address_1");
            entity.Property(e => e.BoardingDate)
                .HasColumnType("datetime")
                .HasColumnName("boarding_date");
            entity.Property(e => e.Country)
                .IsRequired()
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("country");
            entity.Property(e => e.IdPartner)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("id_partner");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
            entity.Property(e => e.Url)
                .HasMaxLength(100)
                .IsUnicode(false)
                .HasColumnName("url");

            entity.HasOne(d => d.IdPartnerNavigation).WithMany(p => p.RMerchants)
                .HasForeignKey(d => d.IdPartner)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__r_merchan__id_pa__398D8EEE");
        });

        modelBuilder.Entity<RPartner>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__r_partne__3213E83F8EA3A9F9");

            entity.ToTable("r_partner");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("id");
            entity.Property(e => e.Name)
                .IsRequired()
                .HasMaxLength(100)
                .HasColumnName("name");
        });

        modelBuilder.Entity<RTransaction>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__r_transa__3213E83F9FD4EBC8");

            entity.ToTable("r_transaction");

            entity.Property(e => e.Id)
                .ValueGeneratedOnAdd()
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("id");
            entity.Property(e => e.Amount)
                .HasColumnType("money")
                .HasColumnName("amount");
            entity.Property(e => e.BeneficiaryIban)
                .IsRequired()
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("beneficiary_iban");
            entity.Property(e => e.CreateDate)
                .HasColumnType("datetime")
                .HasColumnName("create_date");
            entity.Property(e => e.Currency)
                .IsRequired()
                .HasMaxLength(3)
                .IsUnicode(false)
                .HasColumnName("currency");
            entity.Property(e => e.DebtorIban)
                .IsRequired()
                .HasMaxLength(22)
                .IsUnicode(false)
                .HasColumnName("debtor_iban");
            entity.Property(e => e.Direction)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("direction");
            entity.Property(e => e.ExternalId)
                .HasMaxLength(50)
                .IsUnicode(false)
                .HasColumnName("external_id");
            entity.Property(e => e.IdMerchant)
                .HasColumnType("decimal(18, 0)")
                .HasColumnName("id_merchant");
            entity.Property(e => e.Status)
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasColumnName("status");

            entity.HasOne(d => d.IdMerchantNavigation).WithMany(p => p.RTransactions)
                .HasForeignKey(d => d.IdMerchant)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK__r_transac__id_me__3C69FB99");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}